# Generated by Django 3.2.9 on 2021-11-27 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExprTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('expr_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algebra.exprtypes')),
            ],
        ),
    ]
