# Generated by Django 3.2.9 on 2021-12-01 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('algebra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressions',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expressions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exprtypes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exprtypes',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Type of expression'),
        ),
    ]
