# Generated by Django 3.2.9 on 2021-12-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algebra', '0003_alter_expressions_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedExpressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solv_date', models.DateTimeField(auto_now=True)),
                ('expr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algebra.expressions')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
