# Generated by Django 3.2.9 on 2021-12-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algebra', '0004_solvedexpressions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvedexpressions',
            old_name='expr_id',
            new_name='expr',
        ),
        migrations.RenameField(
            model_name='solvedexpressions',
            old_name='user_id',
            new_name='user',
        ),
    ]
