# Generated by Django 3.2.9 on 2021-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algebra', '0005_auto_20211204_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedexpressions',
            name='trys',
            field=models.IntegerField(default=0, verbose_name='Number of trys'),
            preserve_default=False,
        ),
    ]
