# Generated by Django 3.2.9 on 2021-12-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algebra', '0006_solvedexpressions_trys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedexpressions',
            name='trys',
            field=models.IntegerField(default=0, verbose_name='Number of trys'),
        ),
    ]
