# Generated by Django 3.2.9 on 2021-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algebra', '0007_alter_solvedexpressions_trys'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressions',
            name='text_r',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
